topic:
  retry: 'library-events.RETRY'
  dlt: 'library-events.DLT'

spring:
  application:
    name: LibraryEventManagemnetConsumer

  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: library-events-listener-group
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
        #- localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8089

